import { createFileRoute, Link } from "@tanstack/react-router";
import { FolderKanban, Gauge, Users, Zap, Plus, ArrowRight } from "lucide-react";
import { DashboardCard } from "@/components/DashboardCard";
import { ProjectCard } from "@/components/ProjectCard";
import { SkillBarChart } from "@/components/charts/SkillBarChart";
import { RoleDistributionChart } from "@/components/charts/RoleDistributionChart";
import { SkillGapCard } from "@/components/SkillGapCard";
import { AppLayout } from "@/layouts/AppLayout";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useAppStore } from "@/hooks/useAppStore";

export const Route = createFileRoute("/dashboard")({
  head: () => ({
    meta: [
      { title: "Dashboard — TeamForge AI" },
      {
        name: "description",
        content:
          "Track candidates, projects, teams created and average team compatibility across your workspace.",
      },
      { property: "og:title", content: "Dashboard — TeamForge AI" },
      {
        property: "og:description",
        content: "Candidate skill distribution, skill-gap overview and recent projects.",
      },
    ],
  }),
  component: Dashboard,
});

function Dashboard() {
  const { candidates, projects, results, hydrated } = useAppStore();
  const resultList = Object.values(results);
  const avg = resultList.length
    ? Math.round(resultList.reduce((s, r) => s + r.teamScore, 0) / resultList.length)
    : 0;

  const skillCounts = new Map<string, number>();
  candidates.forEach((c) => c.skills.forEach((s) => skillCounts.set(s, (skillCounts.get(s) ?? 0) + 1)));
  const skillData = [...skillCounts.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 10)
    .map(([name, value]) => ({ name, value }));

  const roleCounts = new Map<string, number>();
  candidates.forEach((c) => roleCounts.set(c.role, (roleCounts.get(c.role) ?? 0) + 1));
  const roleData = [...roleCounts.entries()].map(([name, value]) => ({ name, value }));

  const gaps = resultList.flatMap((r) => r.skillGaps).slice(0, 4);

  if (!hydrated) {
    return (
      <AppLayout title="Dashboard" description="Loading your workspace">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-32 rounded-2xl" />
          ))}
        </div>
      </AppLayout>
    );
  }

  return (
    <AppLayout
      title="Dashboard"
      description="Workspace intelligence across candidates, projects and teams."
      actions={
        <>
          <Button asChild variant="secondary">
            <Link to="/candidates">
              <Plus className="h-4 w-4" /> Add candidate
            </Link>
          </Button>
          <Button asChild variant="secondary">
            <Link to="/projects/new">
              <Plus className="h-4 w-4" /> Create project
            </Link>
          </Button>
          <Button asChild>
            <Link to="/team/$projectId" params={{ projectId: projects[0]?.id ?? "p1" }}>
              <Zap className="h-4 w-4" /> Build team
            </Link>
          </Button>
        </>
      }
    >
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <DashboardCard label="Total candidates" value={candidates.length} icon={Users} hint="In your talent pool" index={0} />
        <DashboardCard label="Active projects" value={projects.length} icon={FolderKanban} hint="Awaiting or in delivery" index={1} />
        <DashboardCard label="Teams created" value={resultList.length} icon={Zap} hint="Generated by the AI builder" index={2} />
        <DashboardCard
          label="Avg. compatibility"
          value={resultList.length ? `${avg}/100` : "—"}
          icon={Gauge}
          hint={resultList.length ? "Across all forged teams" : "Build a team to see this"}
          index={3}
        />
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-3">
        <Card className="glass gap-2 p-6 lg:col-span-2">
          <h2 className="font-semibold">Candidate skill distribution</h2>
          <p className="text-sm text-muted-foreground">Top skills across your talent pool</p>
          <SkillBarChart data={skillData} />
        </Card>
        <Card className="glass gap-2 p-6">
          <h2 className="font-semibold">Role distribution</h2>
          <p className="text-sm text-muted-foreground">Coverage by primary role</p>
          <RoleDistributionChart data={roleData} />
        </Card>
      </div>

      <div className="mt-8 space-y-8">
        <div>
          <div className="mb-3 flex items-center justify-between">
            <h2 className="font-semibold">Recent projects</h2>
            <Button asChild variant="ghost" size="sm">
              <Link to="/projects">
                View all <ArrowRight className="h-4 w-4" />
              </Link>
            </Button>
          </div>
          {projects.length ? (
            <div className="grid items-stretch gap-6 sm:grid-cols-2 xl:grid-cols-3">
              {projects.slice(0, 3).map((p, i) => (
                <ProjectCard key={p.id} project={p} result={results[p.id]} index={i} />
              ))}
            </div>
          ) : (
            <Card className="glass items-center gap-3 p-10 text-center">
              <p className="text-sm text-muted-foreground">No projects yet.</p>
              <Button asChild size="sm">
                <Link to="/projects/new">Create your first project</Link>
              </Button>
            </Card>
          )}
        </div>

        <div>
          <h2 className="mb-3 font-semibold">Skill gap overview</h2>
          {gaps.length ? (
            <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
              {gaps.map((g, i) => (
                <SkillGapCard key={`${g.skill}-${i}`} gap={g} index={i} />
              ))}
            </div>
          ) : (
            <Card className="glass items-center gap-3 p-10 text-center">
              <p className="text-sm text-muted-foreground">
                Build a team to reveal skill gaps and learning paths.
              </p>
              <Button asChild size="sm" variant="secondary">
                <Link to="/projects">Build a team</Link>
              </Button>
            </Card>
          )}
        </div>
      </div>
    </AppLayout>
  );
}